server:
  port: 8080
  
Spring:
  application:
    name: Calling_External_Postal_API
    
  jpa:
   hibernate:
     ddl-auto: update
     
     
  datasource:
   url:  jdbc:mysql://localhost:3306/postal_office
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver